### ISSUE TITLE
Why is a ValueError raised?

### ISSUE THREAD

**Issue by NMO13** [mtShaikh/flask-restful-paginate#10]
If the page number is invalid (out of range) an empty list was returned so far. Since the last commit, this two new lines:

```
        if not items:
            raise ValueError("Incorrect signature")
```
are breaking my code. Why is a ValueError raised now?

**Comment by mtShaikh** [comment]
I added functionality for adding an optional post query hook (callback) to support manipulation on data after it has been fetched from the db. For that I need to ensure the signature for the hook was correct. However I, incorrectly raised the `ValueError` for incorrect signature. I have fixed this issue in the latest release.

**Comment by NMO13** [comment]
Thanks for the quick fix!
