### ISSUE TITLE
Allow to customize result keys

### ISSUE THREAD

**Issue by nicolamoro-athonet** [mtShaikh/flask-restful-paginate#15]
At the moment the result object is hardwired with "data" key for result data, and with "pagination" key for pagination data.
It would be useful to be able to customize this keys, in particular:
- allow to change the "data" key (e.g. changing to "results");
- allow to change the "pagination" key, or allow that fields to be directly at the root level of the result object (not nested into a "pagination" key).

I already have a feature branch with this modifications, ready to be pushed to open a PR.... but I'm unable to push (no permissions).
If you're interested let me know.

**Comment by mtShaikh** [comment]
You can fork the repo, push your code there and, then open a PR here. I'll be happy to merge :)

**Comment by mtShaikh** [comment]
I've created a new release featuring this update. Thanks for the contribution @nicolamoro-athonet!

**Comment by nicolamoro** [comment]
Thanks for your time @mtShaikh !
Happy to have contributed!
