### ISSUE TITLE
Paginate not working with SQLAlchemy Table

### ISSUE THREAD

**Issue by alessandrosales** [mtShaikh/flask-restful-paginate#9]
I have a table like this:

```
ReportView = Table(
  'report_view',
  MetaData(),
  Column('col1', db.String),
  Column('col2', db.String)
)
```

But this not working:

```
#...more imports
from flask_restful import fields
report_fields = {
  'col1': fields.String,
  'col2': fields.String
}

context_query = db.session.query(ReportView)
page = pagination.paginate(context_query, report_fields)
```

Issue: In this case, the mapping not working currectly why the result is a list of tuple.

**Comment by mtShaikh** [comment]
This plugin uses the `flask-sqlalchemy`'s [`paginate`](https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/?highlight=paginate#flask_sqlalchemy.BaseQuery.paginate) method. It is a method in the `flask_sqlalchemy.Model` class. It would not work on the `Query` object or `Table` object.

**Comment by alessandrosales** [comment]
Thanks
